interface APIResult {id?:string;error?:string;fields?:Record<string,string>;}
const csrf=()=>document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content||'';
async function api(path:string,body:unknown,method='POST') {const response=await fetch(path,{method,headers:{'Content-Type':'application/json','x-csrf-token':csrf()},body:JSON.stringify(body)});const result=await response.json() as APIResult;return {response,result};}
const login=document.querySelector<HTMLFormElement>('#admin-login');
login?.addEventListener('submit',async e=>{e.preventDefault();const button=login.querySelector<HTMLButtonElement>('button[type=submit]')!;const error=document.querySelector<HTMLElement>('#login-error')!;error.hidden=true;button.disabled=true;try{const {response,result}=await api('/api/admin/login',Object.fromEntries(new FormData(login)));if(response.ok)location.assign('/admin');else{error.textContent=result.error||'Please try again.';error.hidden=false;}}catch{error.textContent='Connection interrupted. Please try signing in again.';error.hidden=false;}finally{button.disabled=false;}});
document.querySelector('[data-logout]')?.addEventListener('click',async()=>{await api('/api/admin/logout',{});location.assign('/admin/login');});
const editor=document.querySelector<HTMLFormElement>('#cms-editor');let dirty=false;editor?.addEventListener('input',()=>dirty=true);
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();}});
editor?.addEventListener('submit',async e=>{
 e.preventDefault();const button=editor.querySelector<HTMLButtonElement>('button[type=submit]')!;const error=document.querySelector<HTMLElement>('#save-error')!;error.hidden=true;document.querySelectorAll<HTMLElement>('[data-error-for]').forEach(el=>el.hidden=true);editor.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));button.disabled=true;
 const fields:Record<string,unknown>={};editor.querySelectorAll<HTMLElement>('.cms-field input,.cms-field textarea,.cms-field select').forEach(element=>{const input=element as HTMLInputElement;fields[input.name]=input instanceof HTMLInputElement&&input.type==='checkbox'?input.checked:input instanceof HTMLInputElement&&input.type==='number'?(input.value===''?null:Number(input.value)):input.value;});
 const payload:Record<string,unknown>={id:editor.dataset.id||undefined,fields};
 if(editor.dataset.entity==='resorts'){payload.gallery=Array.from(document.querySelectorAll<HTMLElement>('[data-gallery-row]')).map(row=>({url:row.dataset.url,alt:row.querySelector<HTMLInputElement>('input')?.value||''}));payload.amenity_ids=new FormData(editor).getAll('amenity_ids');}
 if(editor.dataset.entity==='offers')payload.resort_ids=new FormData(editor).getAll('resort_ids');
 try{const {response,result}=await api(`/api/admin/${editor.dataset.entity}`,payload);if(response.ok){dirty=false;location.assign(`/admin/${editor.dataset.entity}/${result.id}?saved=1`);}else{error.hidden=false;error.textContent=result.error||'Could not save.';if(result.fields)for(const [key,message] of Object.entries(result.fields)){const field=document.getElementById(`field-${key}`);field?.setAttribute('aria-invalid','true');field?.setAttribute('aria-describedby',`field-${key}-error`);const note=document.getElementById(`field-${key}-error`);if(note){note.textContent=String(message);note.hidden=false;}}const first=editor.querySelector<HTMLElement>('[aria-invalid=true]');if(first)first.focus();else{error.tabIndex=-1;error.focus();}}}catch{error.textContent='Your connection was interrupted. Your changes are still in this form; please try again.';error.hidden=false;}finally{button.disabled=false;}
});
const deleteDialog=document.querySelector<HTMLDialogElement>('#delete-dialog');document.querySelector('[data-delete-record]')?.addEventListener('click',()=>deleteDialog?.showModal());document.querySelector('[data-cancel-delete]')?.addEventListener('click',()=>deleteDialog?.close());document.querySelector('[data-confirm-delete]')?.addEventListener('click',async()=>{if(!editor)return;const {response,result}=await api(`/api/admin/${editor.dataset.entity}`,{id:editor.dataset.id},'DELETE');deleteDialog?.close();if(response.ok){dirty=false;location.assign(`/admin/${editor.dataset.entity}?saved=1`);}else{const error=document.querySelector<HTMLElement>('#save-error')!;error.hidden=false;error.textContent=result.error||'Please try again.';}});
type ImageItem={id:string;url:string;filename:string;alt?:string};
const picker=document.querySelector<HTMLDialogElement>('#media-picker');let target:string|null=null;let galleryMode=false;let libraryOnly=false;
const presets:ImageItem[]=['hero','cabin','heritage','vagamon','munnar','wayanad','kochi'].map(name=>({id:name,url:`/images/${name}-1080.webp`,filename:`${name} · Sample collection`}));
async function loadMedia(){const container=document.querySelector('#media-options');if(!container)return;container.replaceChildren();const status=document.querySelector<HTMLElement>('#media-status')!;status.textContent='Loading your photographs…';try{const response=await fetch('/api/admin/media');if(!response.ok)throw new Error();const uploaded=await response.json() as ImageItem[];for(const item of [...uploaded,...presets]){const button=document.createElement('button');button.className='media-option';button.type='button';const img=document.createElement('img');img.src=item.url;img.alt=item.alt||item.filename;img.loading='lazy';const caption=document.createElement('span');caption.textContent=item.filename;button.append(img,caption);button.addEventListener('click',()=>choose(item.url,item.alt||''));container.append(button);}status.textContent='';}catch{status.textContent='We couldn’t load your library. Please close and try again.';}}
async function openPicker(){picker?.showModal();await loadMedia();}
document.querySelectorAll<HTMLButtonElement>('[data-choose-image]').forEach(b=>b.addEventListener('click',()=>{target=b.dataset.chooseImage!;galleryMode=false;libraryOnly=false;void openPicker();}));document.querySelector('[data-add-gallery]')?.addEventListener('click',()=>{galleryMode=true;target=null;void openPicker();});document.querySelectorAll('[data-open-library]').forEach(b=>b.addEventListener('click',()=>{libraryOnly=true;galleryMode=false;target=null;void openPicker();}));document.querySelector('[data-close-picker]')?.addEventListener('click',()=>{picker?.close();if(libraryOnly)location.reload();});
function choose(url:string,alt=''){if(galleryMode)addGallery(url,alt);else if(target){const field=document.querySelector<HTMLInputElement>(`[name="${target}"]`);if(field)field.value=url;const preview=document.querySelector<HTMLImageElement>(`[data-image-preview="${target}"]`);if(preview)preview.src=url;dirty=true;}else if(libraryOnly){navigator.clipboard.writeText(new URL(url,location.origin).href).then(()=>{const status=document.querySelector<HTMLElement>('#media-status')!;status.textContent='Image URL copied.';});return;}picker?.close();}
document.querySelectorAll<HTMLButtonElement>('[data-clear-image]').forEach(b=>b.addEventListener('click',()=>{const input=document.querySelector<HTMLInputElement>(`[name="${b.dataset.clearImage}"]`);if(input)input.value='';const img=document.querySelector<HTMLImageElement>(`[data-image-preview="${b.dataset.clearImage}"]`);if(img)img.src='/images/heritage-640.webp';dirty=true;}));
function addGallery(url:string,alt:string){const rows=document.querySelector('#gallery-rows');if(!rows)return;const row=document.createElement('div');row.className='gallery-edit-row';row.dataset.galleryRow='';row.dataset.url=url;const img=document.createElement('img');img.src=url;img.alt='Gallery image preview';const wrapper=document.createElement('div');const label=document.createElement('label');label.textContent='Image description';const input=document.createElement('input');input.name='gallery_alt';input.value=alt;input.placeholder='Describe this photograph';label.append(input);const actions=document.createElement('div');actions.className='gallery-row-actions';for(const [data,text] of [['galleryUp','↑'],['galleryDown','↓'],['galleryCover','Set as cover'],['galleryRemove','Remove']]){const b=document.createElement('button');b.type='button';b.dataset[data]='';b.textContent=text;if(data==='galleryUp')b.setAttribute('aria-label','Move image earlier');if(data==='galleryDown')b.setAttribute('aria-label','Move image later');actions.append(b);}wrapper.append(label,actions);row.append(img,wrapper);rows.append(row);document.querySelector<HTMLElement>('#gallery-empty')!.hidden=true;dirty=true;}
document.querySelector('#gallery-rows')?.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest('button');if(!button)return;const row=button.closest<HTMLElement>('[data-gallery-row]')!;if('galleryUp'in button.dataset&&row.previousElementSibling)row.parentElement!.insertBefore(row,row.previousElementSibling);if('galleryDown'in button.dataset&&row.nextElementSibling)row.parentElement!.insertBefore(row.nextElementSibling,row);if('galleryRemove'in button.dataset)row.remove();if('galleryCover'in button.dataset){const field=document.querySelector<HTMLInputElement>('[name="cover_image"]');if(field)field.value=row.dataset.url!;const preview=document.querySelector<HTMLImageElement>('[data-image-preview="cover_image"]');if(preview)preview.src=row.dataset.url!;const alt=document.querySelector<HTMLInputElement>('[name="image_alt"]');if(alt)alt.value=row.querySelector<HTMLInputElement>('input')?.value||'';}dirty=true;});
document.querySelector<HTMLInputElement>('[data-media-upload]')?.addEventListener('change',async e=>{const input=e.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;const status=document.querySelector<HTMLElement>('#media-status')!;status.textContent='Optimizing and uploading your photograph…';input.disabled=true;try{if(file.size>30*1024*1024)throw new Error('Choose an image smaller than 30 MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPEG, PNG or WebP image.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1920/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not process this image.')),'image/webp',.84));const body=new FormData();body.set('file',blob,file.name.replace(/\.[^.]+$/,'.webp'));body.set('width',String(canvas.width));body.set('height',String(canvas.height));const response=await fetch('/api/admin/media',{method:'POST',headers:{'x-csrf-token':csrf()},body});const result=await response.json() as APIResult;if(!response.ok)throw new Error(result.error);await loadMedia();status.textContent='Image uploaded. Choose it below to use it.';}catch(error){status.textContent=(error as Error).message||'Could not upload. Please try again.';}finally{input.disabled=false;input.value='';}});
document.querySelectorAll<HTMLButtonElement>('[data-copy-url]').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(new URL(b.dataset.copyUrl!,location.origin).href);document.querySelector('#copy-status')!.textContent='Image URL copied.';}catch{document.querySelector('#copy-status')!.textContent='Copy this image address: '+new URL(b.dataset.copyUrl!,location.origin).href;}}));
