import type { SupabaseClient } from "@supabase/supabase-js";

type Stamped = { updated_at: string; is_demo: number };
export type Location = Stamped & {
  id: string;
  name: string;
  slug: string;
  subtitle: string;
  description: string;
  cover_image: string;
  image_alt: string;
  seo_title: string;
  seo_description: string;
  icon: string;
  featured: number;
  published: number;
  display_order: number;
};
export type Resort = Stamped & {
  id: string;
  name: string;
  slug: string;
  subtitle: string;
  short_description: string;
  description: string;
  location_id: string;
  address: string;
  show_address: number;
  map_url: string;
  property_type: string;
  starting_price: number | null;
  price_label: string;
  weekday_rate: string;
  weekend_rate: string;
  group_package: string;
  extra_guest_info: string;
  pricing_disclaimer: string;
  max_guests: number;
  bedrooms: number | null;
  bathrooms: number | null;
  cover_image: string;
  image_alt: string;
  check_in: string;
  check_out: string;
  whatsapp_override: string;
  seo_title: string;
  seo_description: string;
  featured: number;
  published: number;
  archived: number;
  display_order: number;
};
export type Amenity = Stamped & {
  id: string;
  name: string;
  icon: string;
  category: string;
  active: number;
  display_order: number;
};
export type Offer = Stamped & {
  id: string;
  title: string;
  description: string;
  image: string;
  badge: string;
  promotional_text: string;
  cta_label: string;
  cta_type: string;
  start_date: string;
  end_date: string;
  active: number;
  display_order: number;
};
export type Testimonial = Stamped & {
  id: string;
  name: string;
  location: string;
  rating: number;
  quote: string;
  photo: string;
  resort_id: string | null;
  published: number;
  display_order: number;
};
export type PageContent = Stamped & {
  id: string;
  page: string;
  section: string;
  eyebrow: string;
  title: string;
  body: string;
  image: string;
  cta_label: string;
  cta_url: string;
  display_order: number;
};
export type Settings = {
  id: string;
  site_name: string;
  logo: string;
  favicon: string;
  footer_description: string;
  whatsapp: string;
  phone: string;
  email: string;
  address: string;
  business_hours: string;
  map_url: string;
  greeting: string;
  enquiry_message: string;
  property_template: string;
  cta_label: string;
  floating_enabled: number;
  instagram: string;
  facebook: string;
  youtube: string;
  linkedin: string;
  seo_title: string;
  seo_description: string;
  og_image: string;
  copyright: string;
  show_demo: number;
  updated_at: string;
};
export type NavItem = Stamped & {
  id: string;
  label: string;
  url: string;
  in_header: number;
  in_footer: number;
  display_order: number;
};
export type GalleryImage = {
  id: string;
  resort_id: string;
  url: string;
  alt: string;
  display_order: number;
};
export type Attraction = Stamped & {
  id: string;
  resort_id: string;
  name: string;
  image: string;
  distance: string;
  travel_time: string;
  description: string;
  display_order: number;
};
export type Media = {
  id: string;
  object_key: string;
  filename: string;
  content_type: string;
  size: number;
  alt: string;
  width: number | null;
  height: number | null;
  created_at: string;
};
export type ResortView = Resort & {
  location: Location;
  amenities: Amenity[];
  gallery: GalleryImage[];
  highlights: string[];
  rules: string[];
  attractions: Attraction[];
  offers: Offer[];
};
export type SiteData = {
  settings: Settings;
  resorts: ResortView[];
  locations: Location[];
  amenities: Amenity[];
  offers: (Offer & { resorts: ResortView[] })[];
  testimonials: Testimonial[];
  content: PageContent[];
  navigation: NavItem[];
};
export interface RuntimeEnv {
  supabase: SupabaseClient;
  ADMIN_PASSWORD_HASH?: string;
  ADMIN_USERNAME?: string;
  DEMO_MODE?: string;
  SITE_ORIGIN?: string;
  SUPABASE_STORAGE_BUCKET: string;
}
