import {sqliteTable,text,integer,primaryKey,index} from 'drizzle-orm/sqlite-core';
const timestamps=()=>({updated_at:text('updated_at').notNull(),is_demo:integer('is_demo').notNull().default(0)});
export const locations=sqliteTable('locations',{
 id:text('id').primaryKey(),name:text('name').notNull(),slug:text('slug').notNull().unique(),subtitle:text('subtitle').notNull().default(''),description:text('description').notNull().default(''),cover_image:text('cover_image').notNull().default(''),image_alt:text('image_alt').notNull().default(''),seo_title:text('seo_title').notNull().default(''),seo_description:text('seo_description').notNull().default(''),icon:text('icon').notNull().default('mountain'),featured:integer('featured').notNull().default(0),published:integer('published').notNull().default(1),display_order:integer('display_order').notNull().default(0),...timestamps()
});
export const resorts=sqliteTable('resorts',{
 id:text('id').primaryKey(),name:text('name').notNull(),slug:text('slug').notNull().unique(),subtitle:text('subtitle').notNull().default(''),short_description:text('short_description').notNull().default(''),description:text('description').notNull().default(''),location_id:text('location_id').notNull().references(()=>locations.id,{onDelete:'restrict'}),address:text('address').notNull().default(''),show_address:integer('show_address').notNull().default(0),map_url:text('map_url').notNull().default(''),property_type:text('property_type').notNull().default('Private villa'),starting_price:integer('starting_price'),price_label:text('price_label').notNull().default('/ night onwards'),weekday_rate:text('weekday_rate').notNull().default(''),weekend_rate:text('weekend_rate').notNull().default(''),group_package:text('group_package').notNull().default(''),extra_guest_info:text('extra_guest_info').notNull().default(''),pricing_disclaimer:text('pricing_disclaimer').notNull().default('Prices are indicative and may vary. Contact us on WhatsApp for current pricing and stay details.'),max_guests:integer('max_guests').notNull().default(2),bedrooms:integer('bedrooms'),bathrooms:integer('bathrooms'),cover_image:text('cover_image').notNull().default(''),image_alt:text('image_alt').notNull().default(''),check_in:text('check_in').notNull().default('2:00 PM'),check_out:text('check_out').notNull().default('11:00 AM'),whatsapp_override:text('whatsapp_override').notNull().default(''),seo_title:text('seo_title').notNull().default(''),seo_description:text('seo_description').notNull().default(''),featured:integer('featured').notNull().default(0),published:integer('published').notNull().default(0),archived:integer('archived').notNull().default(0),display_order:integer('display_order').notNull().default(0),...timestamps()
},t=>[index('resort_location_idx').on(t.location_id),index('resort_visibility_idx').on(t.published,t.archived)]);
export const amenities=sqliteTable('amenities',{id:text('id').primaryKey(),name:text('name').notNull(),icon:text('icon').notNull().default('check'),category:text('category').notNull().default('Essentials'),active:integer('active').notNull().default(1),display_order:integer('display_order').notNull().default(0),...timestamps()});
export const resortAmenities=sqliteTable('resort_amenities',{resort_id:text('resort_id').notNull().references(()=>resorts.id,{onDelete:'cascade'}),amenity_id:text('amenity_id').notNull().references(()=>amenities.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.resort_id,t.amenity_id]})]);
export const resortFeatures=sqliteTable('resort_features',{id:text('id').primaryKey(),resort_id:text('resort_id').notNull().references(()=>resorts.id,{onDelete:'cascade'}),kind:text('kind').notNull(),text:text('text').notNull(),display_order:integer('display_order').notNull().default(0)});
export const resortImages=sqliteTable('resort_images',{id:text('id').primaryKey(),resort_id:text('resort_id').notNull().references(()=>resorts.id,{onDelete:'cascade'}),url:text('url').notNull(),alt:text('alt').notNull().default(''),display_order:integer('display_order').notNull().default(0)});
export const nearbyAttractions=sqliteTable('nearby_attractions',{id:text('id').primaryKey(),resort_id:text('resort_id').notNull().references(()=>resorts.id,{onDelete:'cascade'}),name:text('name').notNull(),image:text('image').notNull().default(''),distance:text('distance').notNull().default(''),travel_time:text('travel_time').notNull().default(''),description:text('description').notNull().default(''),display_order:integer('display_order').notNull().default(0),...timestamps()});
export const offers=sqliteTable('offers',{id:text('id').primaryKey(),title:text('title').notNull(),description:text('description').notNull().default(''),image:text('image').notNull().default(''),badge:text('badge').notNull().default(''),promotional_text:text('promotional_text').notNull().default(''),cta_label:text('cta_label').notNull().default('Explore this escape'),cta_type:text('cta_type').notNull().default('resort'),start_date:text('start_date').notNull().default(''),end_date:text('end_date').notNull().default(''),active:integer('active').notNull().default(1),display_order:integer('display_order').notNull().default(0),...timestamps()});
export const offerResorts=sqliteTable('offer_resorts',{offer_id:text('offer_id').notNull().references(()=>offers.id,{onDelete:'cascade'}),resort_id:text('resort_id').notNull().references(()=>resorts.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.offer_id,t.resort_id]})]);
export const testimonials=sqliteTable('testimonials',{id:text('id').primaryKey(),name:text('name').notNull(),location:text('location').notNull().default(''),rating:integer('rating').notNull().default(5),quote:text('quote').notNull(),photo:text('photo').notNull().default(''),resort_id:text('resort_id').references(()=>resorts.id,{onDelete:'set null'}),published:integer('published').notNull().default(0),display_order:integer('display_order').notNull().default(0),...timestamps()});
export const pageContent=sqliteTable('page_content',{id:text('id').primaryKey(),page:text('page').notNull(),section:text('section').notNull(),eyebrow:text('eyebrow').notNull().default(''),title:text('title').notNull().default(''),body:text('body').notNull().default(''),image:text('image').notNull().default(''),cta_label:text('cta_label').notNull().default(''),cta_url:text('cta_url').notNull().default(''),display_order:integer('display_order').notNull().default(0),...timestamps()});
export const siteSettings=sqliteTable('site_settings',{
 id:text('id').primaryKey().default('global'),site_name:text('site_name').notNull().default('Vibe Stayz'),logo:text('logo').notNull().default('/images/brand-round.png'),favicon:text('favicon').notNull().default('/images/brand-round.png'),footer_description:text('footer_description').notNull().default(''),whatsapp:text('whatsapp').notNull().default(''),phone:text('phone').notNull().default(''),email:text('email').notNull().default(''),address:text('address').notNull().default(''),business_hours:text('business_hours').notNull().default(''),map_url:text('map_url').notNull().default(''),greeting:text('greeting').notNull().default('Hi Vibe Stayz,'),enquiry_message:text('enquiry_message').notNull().default('I would love some help finding my next getaway.'),property_template:text('property_template').notNull().default("{greeting}\nI'm interested in {property}, {location}.\n\nCould you please share the current price and stay details?\n\nProperty: {property}\nLocation: {location}\nPage: {url}"),cta_label:text('cta_label').notNull().default('Enquire on WhatsApp'),floating_enabled:integer('floating_enabled').notNull().default(1),instagram:text('instagram').notNull().default(''),facebook:text('facebook').notNull().default(''),youtube:text('youtube').notNull().default(''),linkedin:text('linkedin').notNull().default(''),seo_title:text('seo_title').notNull().default('Vibe Stayz | Private villas & beautiful Kerala escapes'),seo_description:text('seo_description').notNull().default('Discover private villas, mountain cabins and peaceful resorts across Kerala. Find a stay you love and enquire directly on WhatsApp.'),og_image:text('og_image').notNull().default('/images/hero-1680.webp'),copyright:text('copyright').notNull().default('All rights reserved.'),show_demo:integer('show_demo').notNull().default(1),updated_at:text('updated_at').notNull()
});
export const navigation=sqliteTable('navigation',{id:text('id').primaryKey(),label:text('label').notNull(),url:text('url').notNull(),in_header:integer('in_header').notNull().default(1),in_footer:integer('in_footer').notNull().default(1),display_order:integer('display_order').notNull().default(0),...timestamps()});
export const media=sqliteTable('media',{id:text('id').primaryKey(),object_key:text('object_key').notNull(),filename:text('filename').notNull(),content_type:text('content_type').notNull(),size:integer('size').notNull(),alt:text('alt').notNull().default(''),width:integer('width'),height:integer('height'),created_at:text('created_at').notNull()});
export const adminSessions=sqliteTable('admin_sessions',{token_hash:text('token_hash').primaryKey(),expires_at:integer('expires_at').notNull(),created_at:integer('created_at').notNull()});
export const loginAttempts=sqliteTable('login_attempts',{key:text('key').primaryKey(),attempts:integer('attempts').notNull().default(0),reset_at:integer('reset_at').notNull()});
