import { ArrowRight, ChevronRight, ChevronDown, Search, MapPin, Mountain, Leaf, Trees, Waves, Users, BedDouble, Bath, Wifi, Snowflake, Utensils, Car, Flame, Coffee, PawPrint, ShieldCheck, Heart, Headphones, Check, X, Menu, Grid2X2, Mail, Phone, Clock, Star, Settings, Pencil, Plus, Image, LogOut, FileText, Tag, ExternalLink, SlidersHorizontal, CircleHelp, Pause, Play, Share2, MountainSnow, TreePalm, Sailboat, Anchor, Ship, Shell, Fish, Sunset, Sunrise, TentTree, CloudFog, Landmark, Castle, Church, Bird, Flower2, Droplets, Compass, Umbrella, Eye, Monitor, Tablet, Smartphone, RotateCw, type LucideIcon } from "lucide-react";
import { siWhatsapp, siInstagram } from "simple-icons";
const icons: Record<string, LucideIcon> = { arrow:ArrowRight, chevron:ChevronRight, down:ChevronDown, search:Search, pin:MapPin, mountain:Mountain, leaf:Leaf, trees:Trees, waves:Waves, users:Users, bed:BedDouble, bath:Bath, wifi:Wifi, snowflake:Snowflake, utensils:Utensils, car:Car, flame:Flame, coffee:Coffee, paw:PawPrint, shield:ShieldCheck, heart:Heart, headphones:Headphones, check:Check, close:X, menu:Menu, grid:Grid2X2, mail:Mail, phone:Phone, clock:Clock, star:Star, settings:Settings, edit:Pencil, plus:Plus, image:Image, logout:LogOut, file:FileText, offer:Tag, external:ExternalLink, sliders:SlidersHorizontal, help:CircleHelp, pause:Pause, play:Play, share:Share2, eye:Eye, monitor:Monitor, tablet:Tablet, mobile:Smartphone, refresh:RotateCw,
 // Destination icons — chosen from the admin, one per location.
 peak:MountainSnow, palm:TreePalm, boat:Sailboat, anchor:Anchor, ship:Ship, shell:Shell, fish:Fish, sunset:Sunset, sunrise:Sunrise, camp:TentTree, mist:CloudFog, landmark:Landmark, fort:Castle, church:Church, bird:Bird, flower:Flower2, water:Droplets, compass:Compass, umbrella:Umbrella };
export default function Icon({name="arrow",size=22,className=""}:{name?:string;size?:number;className?:string}) {
 if(name==="whatsapp" || name==="instagram") return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" className={className} aria-hidden="true"><path d={name === "whatsapp" ? siWhatsapp.path : siInstagram.path}/></svg>;
 const Component=icons[name]||Check;return <Component size={size} strokeWidth={1.6} className={className} aria-hidden="true"/>;
}
