"use client";
import { useEffect, useState } from "react";
import type { OfferLink } from "@/types";
import { money } from "@/utils/format";
export default function OfferPricingEditor({ stays, links, locationId }: { stays: {id:string;name:string;location_id:string;locationName:string;starting_price:number|null}[]; links:OfferLink[]; locationId:string }) {
 const [location,setLocation]=useState(locationId);const [selected,setSelected]=useState(links.map(l=>l.resort_id));const [prices,setPrices]=useState<Record<string,string>>(Object.fromEntries(links.map(l=>[l.resort_id,l.offer_price==null?"":String(l.offer_price)])));
 useEffect(()=>{const el=document.querySelector<HTMLSelectElement>('[name="location_id"]');const change=()=>setLocation(el?.value||"");el?.addEventListener("change",change);return()=>el?.removeEventListener("change",change);},[]);
 return <section className="admin-panel editor-group"><h2>Participating stays & prices</h2><p className="field-help">Choose stays and set a separate nightly price for each. Leave a price empty for a promotion without a discount. Regular prices are never changed.</p><div className="offer-pricing-list">{stays.filter(r=>!location||r.location_id===location||selected.includes(r.id)).map(r=>{const checked=selected.includes(r.id);const mismatch=!!location&&location!==r.location_id;const p=Number(prices[r.id]);return <div className="offer-price-row" key={r.id} data-offer-stay={r.id}><label><input type="checkbox" name="resort_ids" value={r.id} checked={checked} onChange={e=>setSelected(s=>e.target.checked?[...s,r.id]:s.filter(id=>id!==r.id))}/><span><strong>{r.name}</strong><small>{r.locationName} · Base {money(r.starting_price)}</small>{mismatch&&<small className="field-error">Remove this stay or change the campaign destination.</small>}</span></label><label>Offer price (₹)<input type="number" data-offer-price min="1" max={r.starting_price!=null?r.starting_price-1:undefined} step="1" disabled={!checked||r.starting_price===null} placeholder="No discount" value={prices[r.id]||""} onChange={e=>setPrices({...prices,[r.id]:e.target.value})}/></label><output>{checked&&p>0&&r.starting_price&&p<r.starting_price?`${Math.round((1-p/r.starting_price)*100)}% off`:"—"}</output></div>;})}</div></section>;
}
