import type {PreparedStatement} from '../../../lib/database';
import type {APIRoute} from 'astro';import {ZodError} from 'zod';import {cms} from '../../../lib/cms-config';import {runtime} from '../../../lib/env';import {validateFields,gallerySchema,idsSchema} from '../../../lib/validation';
const usable=(entity:string)=>!!cms[entity];
export const POST:APIRoute=async({request,params})=>{
 const entity=params.entity||'';if(!usable(entity))return Response.json({error:'Unknown content type.'},{status:404});
 try{
 if(Number(request.headers.get('content-length'))>150000)return Response.json({error:'This content is too large.'},{status:413});
 const body=await request.json() as {id?:string;fields:Record<string,unknown>;gallery?:unknown;amenity_ids?:unknown;resort_ids?:unknown};
 const id=entity==='site_settings'?'global':body.id||crypto.randomUUID();if(!/^[a-zA-Z0-9_-]{1,150}$/.test(id))return Response.json({error:'Invalid record.'},{status:400});
 const fields=validateFields(entity,body.fields) as Record<string,string|number|null>;const env=runtime();const current=await env.DB.prepare(`SELECT id FROM ${entity} WHERE id=?`).bind(id).first();
 if(!current){for(const f of cms[entity].groups.flatMap(g=>g.fields).filter(f=>f.required))if(fields[f.key]===undefined||fields[f.key]==='')return Response.json({error:`${f.label} is required.`,fields:{[f.key]:'This field is required.'}},{status:422});}
 if(entity==='offers'&&fields.start_date&&fields.end_date&&String(fields.end_date)<String(fields.start_date))return Response.json({error:'The end date must be on or after the start date.',fields:{end_date:'Choose a later date.'}},{status:422});
 if(entity==='testimonials'&&fields.resort_id==='')fields.resort_id=null;
 fields.updated_at=new Date().toISOString();const keys=Object.keys(fields);const batch:PreparedStatement[]=[];
 if(current)batch.push(env.DB.prepare(`UPDATE ${entity} SET ${keys.map(k=>`${k}=?`).join(',')} WHERE id=?`).bind(...Object.values(fields),id));
 else batch.push(env.DB.prepare(`INSERT INTO ${entity} (id,${keys.join(',')}) VALUES (?,${keys.map(()=>'?').join(',')})`).bind(id,...Object.values(fields)));
 if(entity==='resorts'){
  if(body.gallery!==undefined){const gallery=gallerySchema.parse(body.gallery);batch.push(env.DB.prepare('DELETE FROM resort_images WHERE resort_id=?').bind(id));gallery.forEach((img,i)=>batch.push(env.DB.prepare('INSERT INTO resort_images (id,resort_id,url,alt,display_order) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,img.url,img.alt,i)));}
  if(body.amenity_ids!==undefined){const ids=[...new Set(idsSchema.parse(body.amenity_ids))];batch.push(env.DB.prepare('DELETE FROM resort_amenities WHERE resort_id=?').bind(id));ids.forEach(a=>batch.push(env.DB.prepare('INSERT INTO resort_amenities (resort_id,amenity_id) VALUES (?,?)').bind(id,a)));}
  for(const [field,kind] of [['highlights','highlight'],['rules','rule']]){if(body.fields[field]!==undefined){if(typeof body.fields[field]!=='string'||(body.fields[field] as string).length>10000)throw new Error('Invalid property content');const lines=(body.fields[field] as string).split('\n').map(s=>s.trim()).filter(Boolean).slice(0,25);batch.push(env.DB.prepare('DELETE FROM resort_features WHERE resort_id=? AND kind=?').bind(id,kind));lines.forEach((line,i)=>batch.push(env.DB.prepare('INSERT INTO resort_features (id,resort_id,kind,text,display_order) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,kind,line,i)));}}
 }
 if(entity==='offers'&&body.resort_ids!==undefined){const ids=[...new Set(idsSchema.parse(body.resort_ids))];batch.push(env.DB.prepare('DELETE FROM offer_resorts WHERE offer_id=?').bind(id));ids.forEach(r=>batch.push(env.DB.prepare('INSERT INTO offer_resorts (offer_id,resort_id) VALUES (?,?)').bind(id,r)));}
 await env.DB.batch(batch);return Response.json({ok:true,id});
 }catch(error){if(error instanceof ZodError){const fields=Object.fromEntries(error.issues.map(i=>[i.path.join('.'),i.message]));return Response.json({error:'Please check the highlighted fields.',fields},{status:422});}console.error('CMS save failed',error);const message=String(error);return Response.json({error:message.includes('UNIQUE')?'That page slug is already in use. Choose a different one.':message.includes('FOREIGN KEY')?'A linked destination or resort no longer exists. Refresh and select it again.':'We couldn’t save your changes. Your form is still here; please try again.'},{status:409});}
};
export const DELETE:APIRoute=async({request,params})=>{const entity=params.entity||'';if(!usable(entity)||['site_settings','page_content'].includes(entity))return Response.json({error:'This content cannot be deleted.'},{status:400});try{const {id}=await request.json() as {id:string};if(!id)return Response.json({error:'Select a record.'},{status:400});const env=runtime();if(entity==='resorts')await env.DB.prepare('UPDATE resorts SET archived=1,published=0,updated_at=? WHERE id=?').bind(new Date().toISOString(),id).run();else if(entity==='locations')await env.DB.prepare('UPDATE locations SET published=0,updated_at=? WHERE id=?').bind(new Date().toISOString(),id).run();else await env.DB.prepare(`DELETE FROM ${entity} WHERE id=?`).bind(id).run();return Response.json({ok:true});}catch(error){console.error('CMS removal failed',error);return Response.json({error:'This item is in use or could not be removed. Please try again.'},{status:409});}};
